In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import xarray as xr
import pandas as pd
#from wcmatch.pathlib import Path # Handling of path object
from glob import glob
from plotnine import *
from matplotlib import pyplot as plt
import os
from netCDF4 import Dataset as netcdf_dataset
import math as m
from wcmatch.pathlib import Path # Handling of path object

## load PSSdb dataset, only for UVP and Scanners

In [2]:
PSSdb_1b_files = glob('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/*1b*.csv')
PSSdb_1b_files = [x for x in PSSdb_1b_files if 'IFCB' not in x]

PSSdb_1a_files = glob('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/*1a*.csv')
PSSdb_1a_files = [x for x in PSSdb_1a_files if 'IFCB' not in x]

In [39]:
df_1b=pd.concat(map((lambda path: (pd.read_csv(path))), PSSdb_1b_files)).reset_index(drop=True)
df_1a=pd.concat(map((lambda path: (pd.read_csv(path))), PSSdb_1a_files)).reset_index(drop=True)

## Obtain biovolume data from the Normalized Biovolume values from PSSdb products 1a

In [30]:
np.min(df_1a.biovolume_size_class)

823500.0

In [31]:
print((((np.min(df_1a.biovolume_size_class)*6)/m.pi)**(1./3.)))

116.29338013672985

In [32]:
np.max(df_1a.biovolume_size_class)

27630000000000.0

In [33]:
print((((np.max(df_1a.biovolume_size_class)*6)/m.pi)**(1./3.)))

37508.303448748884

In [13]:
# calculate the size class width, by geometric means:
m = df_1a['biovolume_size_class'].dropna().sort_values().unique()

sqrt2 = np.sqrt(2.0)
width_factor = sqrt2 - 1.0/sqrt2   # ~0.7071067811865476
widths = m * width_factor

bin_width_series = pd.Series(widths, index=m)   # index = midpoint
bin_width_dict = dict(zip(m, widths))

In [20]:
#use dict to assing bin width 
df_1a['biovolume_bin_width'] = df_1a['biovolume_size_class'].map(bin_width_dict)
#calculate biovolume, consider depth integration and liters to cubic meter conversion:
df_1a['biovolume_m2'] =((df_1a['normalized_biovolume_mean']*df_1a['biovolume_bin_width'])/0.001)*df_1a['max_depth']

In [21]:
df_1a_subset = df_1a[df_1a['biovolume_size_class'] <= 4188790204.786391] # equivalent to getting only biomass <2000 um

In [25]:
#modify variable names:
df_1a['month']= df_1a['month'].astype(str).str.zfill(2)
df_1a['year']= df_1a['year'].astype(str)
df_1a['time'] = df_1a.year+df_1a.month
df_1a['time']= pd.to_datetime(df_1a['time'], format = '%Y%m')
df_1a.rename(columns={'latitude':'lat', 'longitude':'lon'}, inplace=True)

df_1a_subset['month']= df_1a_subset['month'].astype(str).str.zfill(2)
df_1a_subset['year']= df_1a_subset['year'].astype(str)
df_1a_subset['time'] = df_1a_subset.year+df_1a_subset.month
df_1a_subset['time']= pd.to_datetime(df_1a_subset['time'], format = '%Y%m')
df_1a_subset.rename(columns={'latitude':'lat', 'longitude':'lon'}, inplace=True)

In [29]:
# sum biovolumes by month, year, latitude and longitude
df_1a_full_biovolume=df_1a.astype(dict(zip(['lat','lon'],[str]*2))).groupby(['lat', 'lon', 'time']).apply(lambda x: pd.Series({'total_biovolume':np.nansum(x.biovolume_m2)}))
                                                                                                       
df_1a_subset_biovolume=df_1a_subset.astype(dict(zip(['lat','lon'],[str]*2))).groupby(['lat', 'lon', 'time']).apply(lambda x: pd.Series({'subset_biovolume':np.nansum(x.biovolume_m2)}))

In [33]:
(f"{np.nanmean(df_1a_full_biovolume.total_biovolume):2e}")

'8.600053e+14'

In [32]:
(f"{np.nanmean(df_1a_subset_biovolume.subset_biovolume):2e}")

'2.027790e+14'

In [68]:
df_1a_subset_biovolume  = df_1a_subset_biovolume.reset_index()
df_1a_full_biovolume = df_1a_full_biovolume.reset_index()

In [69]:
len(df_1a_full_biovolume)

1630

In [70]:
len(df_1a_subset_biovolume)

1629

In [72]:
keys = ['lat','lon','time']
df_1a_biovol = (pd.concat([df_1a_subset_biovolume.set_index(keys), df_1a_full_biovolume.set_index(keys)], axis=1, join='outer').reset_index())

In [73]:
df_1a_biovol

        lat     lon       time  subset_biovolume  total_biovolume
0      -0.5    -0.5 2019-09-01      1.355625e+14     1.434763e+14
1      -0.5  -150.5 2015-04-01      1.317878e+14     1.927846e+14
2      -0.5  -151.5 2015-04-01      1.403267e+14     1.733585e+14
3      -0.5  -153.5 2011-09-01      2.125747e+14     2.309592e+14
4      -0.5   -17.5 2019-10-01      1.283659e+14     1.294859e+14
...     ...     ...        ...               ...              ...
1625    9.5   -28.5 2015-05-01      3.710023e+14     4.181250e+14
1626    9.5   -35.5 2015-05-01      1.357452e+14     1.493039e+14
1627    9.5   -40.5 2015-05-01      1.491927e+14     1.822280e+14
1628    9.5   -80.5 2011-12-01      1.731310e+15     2.031689e+15
1629  -54.5   -64.5 2010-12-01               NaN     2.258448e+12

[1630 rows x 5 columns]

## For 1b: modify variable names, do depth integration, and get monthly gridded averages

In [40]:
#get rid of log scale, convert liters to cubic meters, integrate by depth, and transform back to log
df_1b['intercept_m2'] = np.log10(((10**df_1b.NBSS_intercept_mean)/0.001)*df_1b.max_depth)#df_1b.max_depth

In [41]:
## modify variables to match format from OBGCMs
df_1b['month']= df_1b['month'].astype(str).str.zfill(2)
df_1b['year']= df_1b['year'].astype(str)
df_1b['time'] = df_1b.year+df_1b.month
df_1b['time']= pd.to_datetime(df_1b['time'], format = '%Y%m')
df_1b.rename(columns={'latitude':'lat', 'longitude':'lon'}, inplace=True)

In [43]:
len(df_1b)

1806

In [37]:
np.mean(df_1b.NBSS_slope_mean)

-1.0721057032115173

In [44]:
np.min(df_1b.NBSS_slope_mean)

-2.209

In [45]:
np.max(df_1b.NBSS_slope_mean)

0.0591

In [46]:
10**(np.mean(df_1b.intercept_m2))

38816490623032.414

In [47]:
10**(np.min(df_1b.intercept_m2))

14.658976551654266

In [48]:
10**(np.max(df_1b.intercept_m2))

1.489630114568738e+25

In [49]:
np.mean(df_1b.NBSS_r2_mean)

0.9545465116279069

In [50]:
np.min(df_1b.NBSS_r2_mean)

0.4467

In [51]:
np.max(df_1b.NBSS_r2_mean)

0.9977

In [77]:
pssdb_mean=df_1b.astype(dict(zip(['lat','lon'],[str]*2))).groupby(['lat', 'lon', 'time']).apply(lambda x: pd.Series({'betas_hist':np.nanmean(x.NBSS_slope_mean), 'intercept_hist':np.nanmean(x.intercept_m2),'R2_hist':np.nanmean(x.NBSS_r2_mean)})).reset_index().rename(columns={"latitude": "lat", "longitude": "lon"})
#pssdb_mean = pssdb_mean.astype(dict(zip(['lat','lon'],[float]*2)))
len(pssdb_mean)

1630

In [53]:
pssdb_mean

      lat    lon       time  betas_hist  intercept_hist  R2_hist
0    -0.5   -0.5 2019-09-01     -1.2200       14.840196   0.9821
1    -0.5 -150.5 2015-04-01     -1.1560       14.472196   0.9667
2    -0.5 -151.5 2015-04-01     -1.1430       14.409196   0.9751
3    -0.5 -153.5 2011-09-01     -1.4020       16.873196   0.9836
4    -0.5  -17.5 2019-10-01     -1.3600       15.863196   0.9818
...   ...    ...        ...         ...             ...      ...
1625  9.5  -25.5 2014-04-01     -0.8705       12.225196   0.9876
1626  9.5  -28.5 2015-05-01     -1.0190       13.745196   0.9512
1627  9.5  -35.5 2015-05-01     -1.0870       13.954196   0.9851
1628  9.5  -40.5 2015-05-01     -1.0980       14.019196   0.9701
1629  9.5  -80.5 2011-12-01     -1.1445       14.797674   0.9742

[1630 rows x 6 columns]

## merge biovolume data from 1a with 1b products

In [80]:
pssdb_mean = pd.merge(pssdb_mean, df_1a_biovol,  on=['lat','lon', 'time'], how= 'outer')
pssdb_mean

,lat,lon,time,betas_hist,intercept_hist,R2_hist,subset_biovolume,total_biovolume
0,-0.5,-0.5,2019-09-01,-1.2200,14.840196,0.9821,1.355625e+14,1.434763e+14
1,-0.5,-150.5,2015-04-01,-1.1560,14.472196,0.9667,1.317878e+14,1.927846e+14
2,-0.5,-151.5,2015-04-01,-1.1430,14.409196,0.9751,1.403267e+14,1.733585e+14
3,-0.5,-153.5,2011-09-01,-1.4020,16.873196,0.9836,2.125747e+14,2.309592e+14
4,-0.5,-17.5,2019-10-01,-1.3600,15.863196,0.9818,1.283659e+14,1.294859e+14
...,...,...,...,...,...,...,...,...
1625,9.5,-25.5,2014-04-01,-0.8705,12.225196,0.9876,1.461051e+14,2.226844e+14
1626,9.5,-28.5,2015-05-01,-1.0190,13.745196,0.9512,3.710023e+14,4.181250e+14
1627,9.5,-35.5,2015-05-01,-1.0870,13.954196,0.9851,1.357452e+14,1.493039e+14
1628,9.5,-40.5,2015-05-01,-1.0980,14.019196,0.9701,1.491927e+14,1.822280e+14
1629,9.5,-80.5,2011-12-01,-1.1445,14.797674,0.9742,1.731310e+15,2.031689e+15

In [81]:
pssdb_mean['lat'] = pd.to_numeric(pssdb_mean['lat'], errors='coerce')
pssdb_mean['lon'] = pd.to_numeric(pssdb_mean['lon'], errors='coerce')

## convert PSSdb to xarray so that we can make the conversion of times to seasons

In [82]:
ds_pssdb = pssdb_mean.set_index(['lat', 'lon', 'time']).to_xarray()
ds_pssdb = ds_pssdb.groupby('time.month').mean(dim='time')

In [83]:
ds_pssdb

<xarray.Dataset>
Dimensions:           (lat: 126, lon: 251, month: 12)
Coordinates:
  * lat               (lat) float64 -64.5 -63.5 -62.5 -60.5 ... 78.5 79.5 80.5
  * lon               (lon) float64 -179.5 -178.5 -177.5 ... 175.5 176.5 178.5
  * month             (month) int64 1 2 3 4 5 6 7 8 9 10 11 12
Data variables:
    betas_hist        (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    intercept_hist    (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    R2_hist           (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    subset_biovolume  (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    total_biovolume   (month, lat, lon) float64 nan nan nan nan ... nan nan nan

In [84]:
for var in [ 'betas_hist', 'intercept_hist', 'R2_hist', 'total_biovolume', 'subset_biovolume']: # biomass arrays here 
    SH_subset = ds_pssdb[var].where(ds_pssdb.lat < 0,drop=True).values # selecting southern hemisphere
    SH_subset = np.roll(SH_subset, shift=6, axis=0) #shift the season occurence by six months (only southern hemispher)
    full_field = ds_pssdb[var].values #select biomass values for each of the phytoplankton groups
    full_field[:,0:np.size(SH_subset, axis=1),:] = SH_subset # from full_field biomass subset, select all months (1st dim), 
    #latitudes from 0 to the lenght of southen hemisphere subset (dim2) and all longitudes
    svar = var #+ '_shift' # 
    ds_pssdb[svar] = xr.DataArray(full_field, dims=ds_pssdb[var].dims, coords=ds_pssdb[var].coords)

In [85]:
ds_pssdb

<xarray.Dataset>
Dimensions:           (lat: 126, lon: 251, month: 12)
Coordinates:
  * lat               (lat) float64 -64.5 -63.5 -62.5 -60.5 ... 78.5 79.5 80.5
  * lon               (lon) float64 -179.5 -178.5 -177.5 ... 175.5 176.5 178.5
  * month             (month) int64 1 2 3 4 5 6 7 8 9 10 11 12
Data variables:
    betas_hist        (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    intercept_hist    (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    R2_hist           (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    subset_biovolume  (month, lat, lon) float64 nan nan nan nan ... nan nan nan
    total_biovolume   (month, lat, lon) float64 nan nan nan nan ... nan nan nan

## merge PSSdb and biome datasets

In [86]:
pssdb_mean = ds_pssdb.to_dataframe().reset_index()
pssdb_mean

,lat,lon,month,betas_hist,intercept_hist,R2_hist,subset_biovolume,total_biovolume
0,-64.5,-179.5,1,NaN,NaN,NaN,NaN,NaN
1,-64.5,-179.5,2,NaN,NaN,NaN,NaN,NaN
2,-64.5,-179.5,3,NaN,NaN,NaN,NaN,NaN
3,-64.5,-179.5,4,NaN,NaN,NaN,NaN,NaN
4,-64.5,-179.5,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
379507,80.5,178.5,8,NaN,NaN,NaN,NaN,NaN
379508,80.5,178.5,9,NaN,NaN,NaN,NaN,NaN
379509,80.5,178.5,10,NaN,NaN,NaN,NaN,NaN
379510,80.5,178.5,11,NaN,NaN,NaN,NaN,NaN
379511,80.5,178.5,12,NaN,NaN,NaN,NaN,NaN

In [87]:
pssdb_mean=pssdb_mean.set_index(['lat', 'lon'])
pssdb_mean

              month  betas_hist  intercept_hist  R2_hist  subset_biovolume  \
lat   lon
-64.5 -179.5      1         NaN             NaN      NaN               NaN
      -179.5      2         NaN             NaN      NaN               NaN
      -179.5      3         NaN             NaN      NaN               NaN
      -179.5      4         NaN             NaN      NaN               NaN
      -179.5      5         NaN             NaN      NaN               NaN
...             ...         ...             ...      ...               ...
 80.5  178.5      8         NaN             NaN      NaN               NaN
       178.5      9         NaN             NaN      NaN               NaN
       178.5     10         NaN             NaN      NaN               NaN
       178.5     11         NaN             NaN      NaN               NaN
       178.5     12         NaN             NaN      NaN               NaN

              total_biovolume
lat   lon
-64.5 -179.5              NaN
      -179.5              NaN
      -179.5              NaN
      -179.5              NaN
      -179.5              NaN
...                       ...
 80.5  178.5              NaN
       178.5              NaN
       178.5              NaN
       178.5              NaN
       178.5              NaN

[379512 rows x 6 columns]

In [88]:
biomes_obs= xr.open_mfdataset('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/data_biomes_x1.nc')
biomes_mask = ~np.isnan(biomes_obs.biomes)
biomes_obs['biomes'] = biomes_obs['biomes'].where((biomes_obs['lat'] < 44.5) & (biomes_obs['lat'] > -44.5), 2)
biomes_obs = biomes_obs.where(biomes_mask)
#biomes_obs.biomes.plot()

In [89]:
biomes_obs

<xarray.Dataset>
Dimensions:  (lat: 180, lon: 360)
Coordinates:
  * lat      (lat) float64 89.5 88.5 87.5 86.5 85.5 ... -86.5 -87.5 -88.5 -89.5
  * lon      (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
Data variables:
    biomes   (lat, lon) float64 dask.array<chunksize=(180, 360), meta=np.ndarray>

In [90]:
def area_earth_1deg(lat, lon): # what fraction of the ocean isn in each biome. median by biome, an weigtehd average over the biomes 
    """
    Calculates the surface area of the Earth in a 1-degree grid 
    centered at (lat, lon).
    
    Parameters
    ----------
    lat : float
        Latitude in degrees (center of the grid cell).
    lon : float
        Longitude in degrees (center of the grid cell).
    
    Returns
    -------
    A : float
        Surface area in km^2
    """
    R = 6371.0  # Earth's volumetric mean radius in km
    
    # Convert bounds to radians
    lat1 = np.radians(lat - 0.5)
    lat2 = np.radians(lat + 0.5)
    lon1 = lon - 0.5
    lon2 = lon + 0.5

    # Area calculation
    A = np.pi / 180 * R**2 * abs(np.sin(lat1) - np.sin(lat2)) * abs(lon1 - lon2)
    
    return A

In [91]:
lat2d, lon2d = xr.broadcast(biomes_obs['lat'], biomes_obs['lon'])

cell_area = xr.apply_ufunc(area_earth_1deg, lat2d, lon2d, 
                           vectorize=True, dask='parallelized', output_dtypes=[float]
                           ).assign_attrs(long_name='1° grid cell area (spherical Earth)', units='km^2').rename('cell_area')

biomes_obs = biomes_obs.assign(cell_area=cell_area)

In [93]:
# R version
#area_earth_1deg <- function(lat, lon){
  # calculates the surface area of the earth in a 1 degree grid from the center of the grid
  # inputs in degrees
  #require(oce)
  #pi <- 3.14159265358979323846
  #R <- 6371.0 # Volumetric mean radius of the earth, in km, from nssdc.gsfc.nasa.gov
  #lat1 <- as.radians(lat-0.5)
  #lat2 <- as.radians(lat+0.5)
  #lon1 <- lon-0.5 #longitudes do not need to be in radians  
  #lon2 <- lon+0.5
  #A <- pi / 180 * R^2 * abs(sin(lat1)-sin(lat2)) * abs(lon1-lon2)
  #return(A)
#}

IndentationError: unexpected indent (4014631930.py, line 4)

In [94]:
biomes_obs

<xarray.Dataset>
Dimensions:    (lat: 180, lon: 360)
Coordinates:
  * lat        (lat) float64 89.5 88.5 87.5 86.5 ... -86.5 -87.5 -88.5 -89.5
  * lon        (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
Data variables:
    biomes     (lat, lon) float64 dask.array<chunksize=(180, 360), meta=np.ndarray>
    cell_area  (lat, lon) float64 107.9 107.9 107.9 107.9 ... 107.9 107.9 107.9

In [95]:
biome_vals = [1, 2, 3]
area_list = []
for k in biome_vals:
    area_k = biomes_obs['cell_area'].where(biomes_obs['biomes'] == k).sum(dim=['lat','lon'])
    area_list.append(area_k)

area_by_biome = xr.concat(area_list,
                          dim=xr.DataArray(biome_vals, dims='biomes', name='biomes')) \
                   .rename('area_km2')

area_by_biome = area_by_biome.compute()

df_area = (area_by_biome
      .to_series()                 # index = biome labels
      .rename_axis('biomes')        # name the index
      .reset_index(name='area_km2')# -> 2-column DataFrame
      .sort_values('biomes')
      .reset_index(drop=True)
)
label_map = {1: 'LC', 2: 'HCSS', 3: 'HCPS'}
df_area['biomes'] = df_area['biomes'].map(label_map)

print(df_area)

  biomes      area_km2
0     LC  1.332794e+08
1   HCSS  1.434293e+08
2   HCPS  7.530620e+07

In [57]:
#biomes_obs['betas_obs'] = (('month', 'lat', 'lon'), ds_pssdb.betas_hist.data)

In [96]:
biomes_obs = biomes_obs.to_dataframe()


#common_idx = biomes_obs.index.intersection(pssdb_mean.index)
#biomes_obs = biomes_obs.loc[common_idx]
#df_yield = df_yield.loc[common_idx]

In [97]:
biomes_obs=biomes_obs.reset_index()
biomes_obs

        lat    lon  biomes   cell_area
0      89.5 -179.5     NaN  107.896236
1      89.5 -178.5     NaN  107.896236
2      89.5 -177.5     NaN  107.896236
3      89.5 -176.5     NaN  107.896236
4      89.5 -175.5     NaN  107.896236
...     ...    ...     ...         ...
64795 -89.5  175.5     NaN  107.896236
64796 -89.5  176.5     NaN  107.896236
64797 -89.5  177.5     NaN  107.896236
64798 -89.5  178.5     NaN  107.896236
64799 -89.5  179.5     NaN  107.896236

[64800 rows x 4 columns]

In [98]:
pssdb_biomes = pd.merge(biomes_obs, pssdb_mean, how='left', on= ['lat', 'lon']).reset_index(drop =True)
pssdb_biomes = pssdb_biomes[(pssdb_biomes['betas_hist'].notna()) & (pssdb_biomes['biomes'].notna())].reset_index(drop =True) # check about assigning nearest data

In [99]:
pssdb_biomes

,lat,lon,biomes,cell_area,month,betas_hist,intercept_hist,R2_hist,subset_biovolume,total_biovolume
0,80.5,69.5,2.0,2040.674145,8.0,-0.71160,10.534895,0.94760,6.006215e+13,1.251912e+14
1,79.5,60.5,2.0,2253.188243,8.0,-1.01360,13.587905,0.96615,5.283068e+14,1.134429e+15
2,79.5,66.5,2.0,2253.188243,7.0,-0.72790,11.050613,0.86505,5.067072e+14,2.332618e+15
3,79.5,69.5,2.0,2253.188243,8.0,-0.82940,12.245196,0.98330,3.000293e+14,9.812910e+14
4,79.5,71.5,2.0,2253.188243,7.0,-0.68490,10.892050,0.95075,6.492909e+14,3.713071e+15
...,...,...,...,...,...,...,...,...,...,...
1212,-57.5,-67.5,2.0,6643.255521,7.0,-0.58180,9.593316,0.90310,9.906945e+13,9.906945e+13
1213,-60.5,-60.5,2.0,6088.401114,7.0,-1.01455,13.387113,0.94335,2.897377e+14,4.870905e+14
1214,-62.5,-49.5,2.0,5709.131323,7.0,-0.64370,7.890369,0.97900,5.755103e+11,2.112083e+12
1215,-64.5,-53.5,2.0,5322.905835,7.0,-0.72810,11.329196,0.94540,2.568416e+14,1.074861e+15
1216,-64.5,-52.5,2.0,5322.905835,7.0,-0.87010,10.525723,0.94620,1.860161e+12,4.169276e+12

In [100]:
# assign string with seasons
pssdb_biomes['month'] = pssdb_biomes['month'].astype(str)#.str.zfill(2)
def assign_seasons(month):
    if month in ['12.0', '1.0', '2.0']:
        return 'Winter'
    elif month in ['3.0', '4.0', '5.0']:
        return 'Spring'
    elif month in ['6.0', '7.0', '8.0']:
        return 'Summer'
    elif month in ['9.0', '10.0', '11.0']:
        return 'Fall'
pssdb_biomes['season'] = pssdb_biomes['month'].apply(assign_seasons)
pssdb_biomes.rename(columns={'betas_hist':'slope', 'intercept_hist':'intercept', 'R2_hist':'R2'}, inplace=True)
pssdb_biomes['biomes']=pssdb_biomes['biomes'].astype(str)
pssdb_biomes = pssdb_biomes.replace({'biomes':{'1.0':'LC','2.0':'HCSS','3.0':'HCPS'}})
pssdb_biomes['experiment'] = 'obs'
pssdb_biomes['source'] = 'PSSdb'

In [101]:
pssdb_biomes.season.unique()

array(['Summer', 'Fall', 'Spring', 'Winter'], dtype=object)

In [102]:
pssdb_biomes

,lat,lon,biomes,cell_area,month,slope,intercept,R2,subset_biovolume,total_biovolume,season,experiment,source
0,80.5,69.5,HCSS,2040.674145,8.0,-0.71160,10.534895,0.94760,6.006215e+13,1.251912e+14,Summer,obs,PSSdb
1,79.5,60.5,HCSS,2253.188243,8.0,-1.01360,13.587905,0.96615,5.283068e+14,1.134429e+15,Summer,obs,PSSdb
2,79.5,66.5,HCSS,2253.188243,7.0,-0.72790,11.050613,0.86505,5.067072e+14,2.332618e+15,Summer,obs,PSSdb
3,79.5,69.5,HCSS,2253.188243,8.0,-0.82940,12.245196,0.98330,3.000293e+14,9.812910e+14,Summer,obs,PSSdb
4,79.5,71.5,HCSS,2253.188243,7.0,-0.68490,10.892050,0.95075,6.492909e+14,3.713071e+15,Summer,obs,PSSdb
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1212,-57.5,-67.5,HCSS,6643.255521,7.0,-0.58180,9.593316,0.90310,9.906945e+13,9.906945e+13,Summer,obs,PSSdb
1213,-60.5,-60.5,HCSS,6088.401114,7.0,-1.01455,13.387113,0.94335,2.897377e+14,4.870905e+14,Summer,obs,PSSdb
1214,-62.5,-49.5,HCSS,5709.131323,7.0,-0.64370,7.890369,0.97900,5.755103e+11,2.112083e+12,Summer,obs,PSSdb
1215,-64.5,-53.5,HCSS,5322.905835,7.0,-0.72810,11.329196,0.94540,2.568416e+14,1.074861e+15,Summer,obs,PSSdb
1216,-64.5,-52.5,HCSS,5322.905835,7.0,-0.87010,10.525723,0.94620,1.860161e+12,4.169276e+12,Summer,obs,PSSdb

In [103]:
np.nanmean(pssdb_biomes.intercept)

13.686884409477672

In [104]:
len(pssdb_biomes.loc[pssdb_biomes.biomes=='LC'])

288

In [105]:
len(pssdb_biomes.loc[pssdb_biomes.biomes=='HCSS'])

275

In [106]:
len(pssdb_biomes.loc[pssdb_biomes.biomes=='HCPS'])

654

In [107]:
pssdb_biomes.to_csv('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/PSSdb_data_full.csv', sep= ',', index = False)

In [108]:
def average_Taylor_files(df):
    #print(df.head())
    df =df.astype(dict(zip(['month'],[str]))).groupby(['source','month', 'experiment', 'biomes']).apply(lambda x: pd.Series({

                                                                    'slope':np.nanmean(x.slope),
                                                                    'intercept':np.nanmean(x.intercept),
                                                                    'R2':np.nanmean(x.R2),
                                                                    'total_biovolume':np.nanmean(x.total_biovolume),})).reset_index()
    return df

In [109]:
df_pssdb = pd.read_csv('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/PSSdb_data_full.csv', sep= ',')
df_pssdb= average_Taylor_files(df_pssdb)
df_pssdb.to_csv('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data_Taylor-4.csv', sep= ',', index = False)

In [110]:
#these values need to be filled in, check with jessica
no_biomes=pssdb_biomes[pssdb_biomes['biomes'].isnull()].reset_index(drop =True)
no_biomes

Empty DataFrame
Columns: [lat, lon, biomes, cell_area, month, slope, intercept, R2, subset_biovolume, total_biovolume, season, experiment, source]
Index: []

In [60]:
np.nanmin(10**(pssdb_biomes['intercept']))

1963172.5794218876

In [61]:
np.nanmean(pssdb_biomes['total_biovolume'])

1.0353723149868966e+17

In [62]:
np.nanmax(pssdb_biomes['total_biovolume'])

1.0155444259234976e+19

In [65]:
np.nanmedian(pssdb_biomes['total_biovolume'])

1.0352724622899924e+16

In [63]:
np.nanmean(pssdb_biomes['intercept'])

13.686884409477672

In [64]:
10**(np.nanmean(pssdb_biomes['intercept']))

48627776222910.65

In [107]:
np.nanmedian(10**(pssdb_biomes['intercept']))

37084809925507.48

In [111]:
# get weighted mean by biome
df_pssdb = pd.read_csv('/Users/mc4214/Documents/CMIP6_PSS_paper/data/PSSdb_data/PSSdb_data_full.csv', sep= ',')
df_pssdb['intercept'] = 10**(df_pssdb['intercept'])

In [112]:
df_pssdb

,lat,lon,biomes,cell_area,month,slope,intercept,R2,subset_biovolume,total_biovolume,season,experiment,source
0,80.5,69.5,HCSS,2040.674145,8.0,-0.71160,3.426846e+10,0.94760,6.006215e+13,1.251912e+14,Summer,obs,PSSdb
1,79.5,60.5,HCSS,2253.188243,8.0,-1.01360,3.871730e+13,0.96615,5.283068e+14,1.134429e+15,Summer,obs,PSSdb
2,79.5,66.5,HCSS,2253.188243,7.0,-0.72790,1.123603e+11,0.86505,5.067072e+14,2.332618e+15,Summer,obs,PSSdb
3,79.5,69.5,HCSS,2253.188243,8.0,-0.82940,1.758717e+12,0.98330,3.000293e+14,9.812910e+14,Summer,obs,PSSdb
4,79.5,71.5,HCSS,2253.188243,7.0,-0.68490,7.799207e+10,0.95075,6.492909e+14,3.713071e+15,Summer,obs,PSSdb
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1212,-57.5,-67.5,HCSS,6643.255521,7.0,-0.58180,3.920266e+09,0.90310,9.906945e+13,9.906945e+13,Summer,obs,PSSdb
1213,-60.5,-60.5,HCSS,6088.401114,7.0,-1.01455,2.438445e+13,0.94335,2.897377e+14,4.870905e+14,Summer,obs,PSSdb
1214,-62.5,-49.5,HCSS,5709.131323,7.0,-0.64370,7.769074e+07,0.97900,5.755103e+11,2.112083e+12,Summer,obs,PSSdb
1215,-64.5,-53.5,HCSS,5322.905835,7.0,-0.72810,2.134008e+11,0.94540,2.568416e+14,1.074861e+15,Summer,obs,PSSdb
1216,-64.5,-52.5,HCSS,5322.905835,7.0,-0.87010,3.355238e+10,0.94620,1.860161e+12,4.169276e+12,Summer,obs,PSSdb

In [113]:
pssdb_median_by_biome= df_pssdb.groupby(['biomes']).apply(lambda x: pd.Series({
                                                                    'median_slope':np.nanmean(x.slope),
                                                                    'median_intercept':np.nanmean(x.intercept),
                                                                    'subset_biovolume_median':np.nanmean(x.subset_biovolume),
                                                                    'total_biovolume_median':np.nanmean(x.total_biovolume)})).reset_index()
pssdb_median_by_biome

,biomes,median_slope,median_intercept,subset_biovolume_median,total_biovolume_median
0,HCPS,-1.051808,2.277728e+22,1.993110e+14,3.705817e+14
1,HCSS,-1.015279,1.538362e+19,3.935590e+14,3.377950e+15
2,LC,-1.170604,3.571293e+17,1.092863e+14,1.442346e+14

In [114]:
pssdb_median_by_biome = pssdb_median_by_biome.merge(
    df_area, on='biomes', how='left', validate='m:1'
)
pssdb_median_by_biome

,biomes,median_slope,median_intercept,subset_biovolume_median,total_biovolume_median,area_km2
0,HCPS,-1.051808,2.277728e+22,1.993110e+14,3.705817e+14,7.530620e+07
1,HCSS,-1.015279,1.538362e+19,3.935590e+14,3.377950e+15,1.434293e+08
2,LC,-1.170604,3.571293e+17,1.092863e+14,1.442346e+14,1.332794e+08

In [115]:
cols = ['median_slope', 'median_intercept', 'subset_biovolume_median', 'total_biovolume_median']
w = pssdb_median_by_biome['area_km2'].to_numpy()

def wmean(x, w):
    return np.average(x, weights=w)

area_weighted = {f'{c}_wmean': (f"{wmean(pssdb_median_by_biome[c].to_numpy(), w):2e}") for c in cols}
area_weighted

{'median_slope_wmean': '-1.081903e+00',
 'median_intercept_wmean': '4.879125e+21',
 'subset_biovolume_median_wmean': '2.443728e+14',
 'total_biovolume_median_wmean': '1.510242e+15'}

In [50]:
f"{np.nanmin(df_pssdb.total_biovolume):2e}"

'3.103791e+13'

In [51]:
f"{np.nanmax(df_pssdb.total_biovolume):2e}"

'2.860128e+15'